# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.10
#
# <auto-generated>
#
# Generated from file `Calculator.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module Demo
_M_Demo = Ice.openModule('Demo')
__name__ = 'Demo'

if 'DivisionByZero' not in _M_Demo.__dict__:
    _M_Demo.DivisionByZero = Ice.createTempClass()
    class DivisionByZero(Ice.UserException):
        def __init__(self, reason=''):
            self.reason = reason

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::Demo::DivisionByZero'

    _M_Demo._t_DivisionByZero = IcePy.defineException('::Demo::DivisionByZero', DivisionByZero, (), False, None, (('reason', (), IcePy._t_string, False, 0),))
    DivisionByZero._ice_type = _M_Demo._t_DivisionByZero

    _M_Demo.DivisionByZero = DivisionByZero
    del DivisionByZero

_M_Demo._t_Calculator = IcePy.defineValue('::Demo::Calculator', Ice.Value, -1, (), False, True, None, ())

if 'CalculatorPrx' not in _M_Demo.__dict__:
    _M_Demo.CalculatorPrx = Ice.createTempClass()
    class CalculatorPrx(Ice.ObjectPrx):

        def sum(self, op1, op2, context=None):
            return _M_Demo.Calculator._op_sum.invoke(self, ((op1, op2), context))

        def sumAsync(self, op1, op2, context=None):
            return _M_Demo.Calculator._op_sum.invokeAsync(self, ((op1, op2), context))

        def begin_sum(self, op1, op2, _response=None, _ex=None, _sent=None, context=None):
            return _M_Demo.Calculator._op_sum.begin(self, ((op1, op2), _response, _ex, _sent, context))

        def end_sum(self, _r):
            return _M_Demo.Calculator._op_sum.end(self, _r)

        def sub(self, op1, op2, context=None):
            return _M_Demo.Calculator._op_sub.invoke(self, ((op1, op2), context))

        def subAsync(self, op1, op2, context=None):
            return _M_Demo.Calculator._op_sub.invokeAsync(self, ((op1, op2), context))

        def begin_sub(self, op1, op2, _response=None, _ex=None, _sent=None, context=None):
            return _M_Demo.Calculator._op_sub.begin(self, ((op1, op2), _response, _ex, _sent, context))

        def end_sub(self, _r):
            return _M_Demo.Calculator._op_sub.end(self, _r)

        def mult(self, op1, op2, context=None):
            return _M_Demo.Calculator._op_mult.invoke(self, ((op1, op2), context))

        def multAsync(self, op1, op2, context=None):
            return _M_Demo.Calculator._op_mult.invokeAsync(self, ((op1, op2), context))

        def begin_mult(self, op1, op2, _response=None, _ex=None, _sent=None, context=None):
            return _M_Demo.Calculator._op_mult.begin(self, ((op1, op2), _response, _ex, _sent, context))

        def end_mult(self, _r):
            return _M_Demo.Calculator._op_mult.end(self, _r)

        def div(self, op1, op2, context=None):
            return _M_Demo.Calculator._op_div.invoke(self, ((op1, op2), context))

        def divAsync(self, op1, op2, context=None):
            return _M_Demo.Calculator._op_div.invokeAsync(self, ((op1, op2), context))

        def begin_div(self, op1, op2, _response=None, _ex=None, _sent=None, context=None):
            return _M_Demo.Calculator._op_div.begin(self, ((op1, op2), _response, _ex, _sent, context))

        def end_div(self, _r):
            return _M_Demo.Calculator._op_div.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_Demo.CalculatorPrx.ice_checkedCast(proxy, '::Demo::Calculator', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_Demo.CalculatorPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::Demo::Calculator'
    _M_Demo._t_CalculatorPrx = IcePy.defineProxy('::Demo::Calculator', CalculatorPrx)

    _M_Demo.CalculatorPrx = CalculatorPrx
    del CalculatorPrx

    _M_Demo.Calculator = Ice.createTempClass()
    class Calculator(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Demo::Calculator', '::Ice::Object')

        def ice_id(self, current=None):
            return '::Demo::Calculator'

        @staticmethod
        def ice_staticId():
            return '::Demo::Calculator'

        def sum(self, op1, op2, current=None):
            raise NotImplementedError("servant method 'sum' not implemented")

        def sub(self, op1, op2, current=None):
            raise NotImplementedError("servant method 'sub' not implemented")

        def mult(self, op1, op2, current=None):
            raise NotImplementedError("servant method 'mult' not implemented")

        def div(self, op1, op2, current=None):
            raise NotImplementedError("servant method 'div' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_Demo._t_CalculatorDisp)

        __repr__ = __str__

    _M_Demo._t_CalculatorDisp = IcePy.defineClass('::Demo::Calculator', Calculator, (), None, ())
    Calculator._ice_type = _M_Demo._t_CalculatorDisp

    Calculator._op_sum = IcePy.Operation('sum', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_double, False, 0), ((), IcePy._t_double, False, 0)), (), ((), IcePy._t_double, False, 0), ())
    Calculator._op_sub = IcePy.Operation('sub', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_double, False, 0), ((), IcePy._t_double, False, 0)), (), ((), IcePy._t_double, False, 0), ())
    Calculator._op_mult = IcePy.Operation('mult', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_double, False, 0), ((), IcePy._t_double, False, 0)), (), ((), IcePy._t_double, False, 0), ())
    Calculator._op_div = IcePy.Operation('div', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_double, False, 0), ((), IcePy._t_double, False, 0)), (), ((), IcePy._t_double, False, 0), (_M_Demo._t_DivisionByZero,))

    _M_Demo.Calculator = Calculator
    del Calculator

# End of module Demo
